### ISSUE TITLE
スケジュール出力の際に曜日も表示したい

### ISSUE THREAD

**Issue by heyogino** [kibutan/discordbot-replit#1]
## 概要

スケジュール出力の際に、年月日で出力しているが
分かりやすさのため曜日も併せて表示するようにしたい

**Comment by kibutan** [comment]
日付の取得元として[Google Spead Sheet](https://docs.google.com/spreadsheets/d/1saWrdjSqAp9P09cFQ0VgTMbYAjLwVnreft44vvM1mVg/edit?usp=sharing)を利用しておりまして、今回はその書式を変更することで対処致しました。
